### ISSUE TITLE
Investigate use of low-precision floats

### ISSUE THREAD

**Issue by jaberg** [nengo/nengo-ocl#1]
OpenCL offers the possibility of using e.g. float16 or even float8 numbers. Can the simulator still work at such low precision? Does it go faster?

**Comment by drasmuss** [comment]
We don't have any plans to add this to Nengo OCL at the moment, as we expect the performance benefits to be minor if any. Low precision floats can be used in Nengo core and Nengo DL for anyone that wants to experiment.
