### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by hunse** [nengo/nengo-ocl#120]
From nengo/nengo#1035:

> I ran some memory benchmarks measuring the [unique set size](https://en.wikipedia.org
> /wiki/Unique_set_size). With my n-back model both the reference and optimized reference simulatar take slightly below 170MB. Nengo OCL requires up to 320MB. For a circular convolution with 500 neurons per dimension and 500 dimensions the optimizer requires slightly more memory than the reference backend: 345 vs 312MB. Nengo OCL exceeds this again with up to 473MB.

I think this is mostly due to creating a RaggedArray for all the data on the host, then copying this to the device (which for these tests I believe was the same as the host). This RaggedArray is not needed. (Though it might make resetting faster because it creates a contiguous memory block on the host which is easier to copy to the device. That said, resetting by copying over all the data also copies many things that don't need to be reset because they're read-only, like encoders, decoders, etc.)

**Comment by drasmuss** [comment]
Closing since we don't have any plans to optimize Nengo OCL's memory usage further. We'd recommend people check out [NengoDL](https://github.com/nengo/nengo-dl) if they need to run large models.
