### ISSUE TITLE
atal error C1083: Cannot open include file: 'CL/cl.h': No such file or > directory

### ISSUE THREAD

**Issue by assadRasheed** [nengo/nengo-ocl#152]
(C:\Users\zaid-pc\Anaconda3.0) C:\Users\zaid-pc>pip3 install F:\Users\z-pc\De
sktop\pyopencl-2015.1\pyopencl-2015.1
Processing f:\users\zaid-pc\desktop\pyopencl-2015.1\pyopencl-2015.1
Requirement already satisfied: numpy in c:\python34\lib\site-packages (from pyop
encl==2015.1)
Requirement already satisfied: pytools>=2014.2 in c:\python34\lib\site-packages
(from pyopencl==2015.1)
Requirement already satisfied: pytest>=2 in c:\python34\lib\site-packages (from
pyopencl==2015.1)
Requirement already satisfied: decorator>=3.2.0 in c:\python34\lib\site-packages
 (from pyopencl==2015.1)
Requirement already satisfied: appdirs>=1.4.0 in c:\python34\lib\site-packages (
from pyopencl==2015.1)
Requirement already satisfied: six>=1.8.0 in c:\python34\lib\site-packages (from
 pytools>=2014.2->pyopencl==2015.1)
Requirement already satisfied: py>=1.5.0 in c:\python34\lib\site-packages (from
pytest>=2->pyopencl==2015.1)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\python34\
lib\site-packages (from pytest>=2->pyopencl==2015.1)
Requirement already satisfied: pluggy<0.7,>=0.5 in c:\python34\lib\site-packages
 (from pytest>=2->pyopencl==2015.1)
Requirement already satisfied: attrs>=17.2.0 in c:\python34\lib\site-packages (f
rom pytest>=2->pyopencl==2015.1)
Requirement already satisfied: setuptools in c:\python34\lib\site-packages (from
 pytest>=2->pyopencl==2015.1)
Building wheels for collected packages: pyopencl
  Running setup.py bdist_wheel for pyopencl ... error
  Complete output from command c:\python34\python.exe -u -c "import setuptools,
tokenize;__file__='C:\\Users\\zaid-pc\\AppData\\Local\\Temp\\pip-yfpncjqd-build\
\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r
\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Us
ers\zaid-pc\AppData\Local\Temp\tmp0t5prix4pip-wheel- --python-tag cp34:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.4
  creating build\lib.win32-3.4\pyopencl
  copying pyopencl\algorithm.py -> build\lib.win32-3.4\pyopencl
  copying pyopencl\array.py -> build\lib.win32-3.4\pyopencl
  copying pyopencl\cache.py -> build\lib.win32-3.4\pyopencl
  copying pyopencl\capture_call.py -> build\lib.win32-3.4\pyopencl
  copying pyopencl\clmath.py -> build\lib.win32-3.4\pyopencl
  copying pyopencl\clrandom.py -> build\lib.win32-3.4\pyopencl
  copying pyopencl\elementwise.py -> build\lib.win32-3.4\pyopencl
  copying pyopencl\ipython_ext.py -> build\lib.win32-3.4\pyopencl
  copying pyopencl\reduction.py -> build\lib.win32-3.4\pyopencl
  copying pyopencl\scan.py -> build\lib.win32-3.4\pyopencl
  copying pyopencl\tools.py -> build\lib.win32-3.4\pyopencl
  copying pyopencl\version.py -> build\lib.win32-3.4\pyopencl
  copying pyopencl\_cluda.py -> build\lib.win32-3.4\pyopencl
  copying pyopencl\_mymako.py -> build\lib.win32-3.4\pyopencl
  copying pyopencl\__init__.py -> build\lib.win32-3.4\pyopencl
  creating build\lib.win32-3.4\pyopencl\characterize
  copying pyopencl\characterize\performance.py -> build\lib.win32-3.4\pyopencl\c
haracterize
  copying pyopencl\characterize\__init__.py -> build\lib.win32-3.4\pyopencl\char
acterize
  creating build\lib.win32-3.4\pyopencl\compyte
  copying pyopencl\compyte\array.py -> build\lib.win32-3.4\pyopencl\compyte
  copying pyopencl\compyte\dtypes.py -> build\lib.win32-3.4\pyopencl\compyte
  copying pyopencl\compyte\__init__.py -> build\lib.win32-3.4\pyopencl\compyte
  creating build\lib.win32-3.4\pyopencl\cl
  copying pyopencl\cl\pyopencl-airy.cl -> build\lib.win32-3.4\pyopencl\cl
  copying pyopencl\cl\pyopencl-bessel-j.cl -> build\lib.win32-3.4\pyopencl\cl
  copying pyopencl\cl\pyopencl-bessel-y.cl -> build\lib.win32-3.4\pyopencl\cl
  copying pyopencl\cl\pyopencl-eval-tbl.cl -> build\lib.win32-3.4\pyopencl\cl
  copying pyopencl\cl\pyopencl-ranluxcl.cl -> build\lib.win32-3.4\pyopencl\cl
  copying pyopencl\cl\pyopencl-complex.h -> build\lib.win32-3.4\pyopencl\cl
  Skipping optional fixer: buffer
  Skipping optional fixer: idioms
  Skipping optional fixer: set_literal
  Skipping optional fixer: ws_comma
  running build_ext
  building '_cl' extension
  creating build\temp.win32-3.4
  creating build\temp.win32-3.4\Release
  creating build\temp.win32-3.4\Release\src
  creating build\temp.win32-3.4\Release\src\wrapper
  creating build\temp.win32-3.4\Release\bpl-subset
  creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset
  creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs
  creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\python
  creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\python\src
  creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\python\src\co
nverter
  creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\python\src\ob
ject
  creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\smart_ptr
  creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\smart_ptr\src

  creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\system
  creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\system\src
  creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\thread
  creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\thread\src
  creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\thread\src\wi
n32
  C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /
Ox /MD /W3 /GS- /DNDEBUG -DPYGPU_PACKAGE=pyopencl -DBOOST_PYTHON_SOURCE=1 -DBOOS
T_THREAD_DONT_USE_CHRONO=1 -DPYGPU_PYOPENCL=1 -Dboost=pyopenclboost -DBOOST_THRE
AD_BUILD_DLL=1 -DBOOST_ALL_NO_LIB=1 -DPYOPENCL_USE_DEVICE_FISSION=1 -DBOOST_MULT
I_INDEX_DISABLE_SERIALIZATION=1 -Ibpl-subset/bpl_subset -Ic:\python34\lib\site-p
ackages\numpy\core\include -Ic:\python34\lib\site-packages\numpy\core\include -I
c:\python34\include -Ic:\python34\include /Tpsrc/wrapper/wrap_cl.cpp /Fobuild\te
mp.win32-3.4\Release\src/wrapper/wrap_cl.obj
  wrap_cl.cpp
  c:\users\zaid-pc\appdata\local\temp\pip-yfpncjqd-build\src\wrapper\wrap_cl.hpp
(28) : fatal error C1083: Cannot open include file: 'CL/cl.h': No such file or d
irectory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN
\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for pyopencl
  Running setup.py clean for pyopencl
Failed to build pyopencl
Installing collected packages: pyopencl
  Found existing installation: pyopencl 2017.2.2+cl12
    Uninstalling pyopencl-2017.2.2+cl12:
      Successfully uninstalled pyopencl-2017.2.2+cl12
  Running setup.py install for pyopencl ... error
    Complete output from command c:\python34\python.exe -u -c "import setuptools
, tokenize;__file__='C:\\Users\\zaid-pc\\AppData\\Local\\Temp\\pip-yfpncjqd-buil
d\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('
\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C
:\Users\zaid-pc\AppData\Local\Temp\pip-9x9puf9l-record\install-record.txt --sing
le-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.4
    creating build\lib.win32-3.4\pyopencl
    copying pyopencl\algorithm.py -> build\lib.win32-3.4\pyopencl
    copying pyopencl\array.py -> build\lib.win32-3.4\pyopencl
    copying pyopencl\cache.py -> build\lib.win32-3.4\pyopencl
    copying pyopencl\capture_call.py -> build\lib.win32-3.4\pyopencl
    copying pyopencl\clmath.py -> build\lib.win32-3.4\pyopencl
    copying pyopencl\clrandom.py -> build\lib.win32-3.4\pyopencl
    copying pyopencl\elementwise.py -> build\lib.win32-3.4\pyopencl
    copying pyopencl\ipython_ext.py -> build\lib.win32-3.4\pyopencl
    copying pyopencl\reduction.py -> build\lib.win32-3.4\pyopencl
    copying pyopencl\scan.py -> build\lib.win32-3.4\pyopencl
    copying pyopencl\tools.py -> build\lib.win32-3.4\pyopencl
    copying pyopencl\version.py -> build\lib.win32-3.4\pyopencl
    copying pyopencl\_cluda.py -> build\lib.win32-3.4\pyopencl
    copying pyopencl\_mymako.py -> build\lib.win32-3.4\pyopencl
    copying pyopencl\__init__.py -> build\lib.win32-3.4\pyopencl
    creating build\lib.win32-3.4\pyopencl\characterize
    copying pyopencl\characterize\performance.py -> build\lib.win32-3.4\pyopencl
\characterize
    copying pyopencl\characterize\__init__.py -> build\lib.win32-3.4\pyopencl\ch
aracterize
    creating build\lib.win32-3.4\pyopencl\compyte
    copying pyopencl\compyte\array.py -> build\lib.win32-3.4\pyopencl\compyte
    copying pyopencl\compyte\dtypes.py -> build\lib.win32-3.4\pyopencl\compyte
    copying pyopencl\compyte\__init__.py -> build\lib.win32-3.4\pyopencl\compyte

    creating build\lib.win32-3.4\pyopencl\cl
    copying pyopencl\cl\pyopencl-airy.cl -> build\lib.win32-3.4\pyopencl\cl
    copying pyopencl\cl\pyopencl-bessel-j.cl -> build\lib.win32-3.4\pyopencl\cl
    copying pyopencl\cl\pyopencl-bessel-y.cl -> build\lib.win32-3.4\pyopencl\cl
    copying pyopencl\cl\pyopencl-eval-tbl.cl -> build\lib.win32-3.4\pyopencl\cl
    copying pyopencl\cl\pyopencl-ranluxcl.cl -> build\lib.win32-3.4\pyopencl\cl
    copying pyopencl\cl\pyopencl-complex.h -> build\lib.win32-3.4\pyopencl\cl
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    building '_cl' extension
    creating build\temp.win32-3.4
    creating build\temp.win32-3.4\Release
    creating build\temp.win32-3.4\Release\src
    creating build\temp.win32-3.4\Release\src\wrapper
    creating build\temp.win32-3.4\Release\bpl-subset
    creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset
    creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs
    creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\python
    creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\python\src
    creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\python\src\
converter
    creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\python\src\
object
    creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\smart_ptr
    creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\smart_ptr\s
rc
    creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\system
    creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\system\src
    creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\thread
    creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\thread\src
    creating build\temp.win32-3.4\Release\bpl-subset\bpl_subset\libs\thread\src\
win32
    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo
 /Ox /MD /W3 /GS- /DNDEBUG -DBOOST_THREAD_DONT_USE_CHRONO=1 -Dboost=pyopenclboos
t -DBOOST_PYTHON_SOURCE=1 -DPYGPU_PYOPENCL=1 -DBOOST_MULTI_INDEX_DISABLE_SERIALI
ZATION=1 -DBOOST_ALL_NO_LIB=1 -DBOOST_THREAD_BUILD_DLL=1 -DPYGPU_PACKAGE=pyopenc
l -DPYOPENCL_USE_DEVICE_FISSION=1 -Ibpl-subset/bpl_subset -Ic:\python34\lib\site
-packages\numpy\core\include -Ic:\python34\lib\site-packages\numpy\core\include
-Ic:\python34\include -Ic:\python34\include /Tpsrc/wrapper/wrap_cl.cpp /Fobuild\
temp.win32-3.4\Release\src/wrapper/wrap_cl.obj
    wrap_cl.cpp
    c:\users\zaid-pc\appdata\local\temp\pip-yfpncjqd-build\src\wrapper\wrap_cl.h
pp(28) : fatal error C1083: Cannot open include file: 'CL/cl.h': No such file or
 directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\B
IN\\cl.exe' failed with exit status 2

    ----------------------------------------
  Rolling back uninstall of pyopencl
Command "c:\python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\
\Users\\zaid-pc\\AppData\\Local\\Temp\\pip-yfpncjqd-build\\setup.py';f=getattr(t
okenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();e
xec(compile(code, __file__, 'exec'))" install --record C:\Users\zaid-pc\AppData\
Local\Temp\pip-9x9puf9l-record\install-record.txt --single-version-externally-ma
naged --compile" failed with error code 1 in C:\Users\zaid-pc\AppData\Local\Temp
\pip-yfpncjqd-build\

(C:\Users\zaid-pc\Anaconda3.0) C:\Users\zaid-pc>

**Comment by hunse** [comment]
This appears to be an OpenCL issue. I'm not familiar with installing OpenCL on Windows, but hopefully some quick Google searches can help you. This (blog)[https://streamhpc.com/blog/2015-03-16/how-to-install-opencl-on-windows/] could be a decent place to start.
