### ISSUE TITLE
nengo_ocl in the nengo GUI

### ISSUE THREAD

**Issue by Kanaderu** [nengo/nengo-ocl#161]
Hello,

I've been running into an issue running `nengo_ocl` within the nengo GUI using `nengo --backend=nengo_ocl`. Running any model runs briefly or simulates for a few seconds before throwing an exception: 

```
terminate called after throwing an instance of 'std::runtime_error'
  what(): pybind11_object_dealloc(): Tried to deallocate unregistered instance!
[1]       17392 abort (core dumped) nengo --backend=nengo_ocl
```

Running the simulator explicitly in the code (without the GUI) works without throwing an exception.

Current environment:
python v2.7.12

nengo v2.8.0
nengo-gui v0.4.3
nengo-ocl v1.4.0
pyopencl v2018.2
pybind11 v2.2.4

**Comment by drasmuss** [comment]
I think this should work in more recent nengo versions, let us know if not!
