### ISSUE TITLE
nengoocl profile

### ISSUE THREAD

**Issue by assadRasheed** [nengo/nengo-ocl#164]
i am running code using nengo and found that line   parser.add_argument('--ocl-profile', action='store_true', help="Profile Nengo OCL").what is this object and how to access this .

**Comment by hunse** [comment]
Can you please post this in the [Nengo forum](https://forum.nengo.ai/c/backends), since this is a question? (The Issues here are reserved for problems with the software that you wish to let us know about.)

Also, please include information about where you found this line in your forum post.
