### ISSUE TITLE
Multiple GPU support

### ISSUE THREAD

**Issue by lordNil** [nengo/nengo-ocl#166]
Hello

Sorry for posting here, but I just wanted to ask a question. 

I am doing research, and making large scale models. 
Currently, I have access to a computer with multiple AMD GPU's
does nengo-ocl support multiple GPU's?

Thanks

**Comment by hunse** [comment]
At this time, NengoOCL does not support using multiple GPUs for running a single model (i.e. within the same `nengo_ocl.Simulator` instance). We haven't built out any of the infrastructure needed to partition a model between multiple GPUs (i.e. decide what's running on each GPU), and move memory between GPUs as needed.

You can take advantage of multiple GPUs by running different models (or copies of the same model) on different GPUs using different `nengo_ocl.Simulator` instances. All you need to do is pass the appropriate [PyOpenCL context](https://documen.tician.de/pyopencl/runtime_platform.html#context) to each `Simulator`. The one trick is if you want them to run in parallel, you would need to create parallel Python threads or processes. Probably the easiest way to do this is to start multiple Python instances of your script; you can use the `PYOPENCL_CTX` environment variable to select the context for each script.
