### ISSUE TITLE
Multiple timescales

### ISSUE THREAD

**Issue by jaberg** [nengo/nengo-ocl#3]
There are some things (e.g. data read-out, sync between multiple platforms) that don't have to happen as fast as synapses operate (~1ms) but still regularly and somewhat fast (~10ms).  Consider formalizing this mechanism so that the "make_probe" functionality of Network can be ported to the OpenCL code.

Related: video input at e.g. 25 or 50 fps changes video buffer far less frequently than the synapse rate.

**Comment by drasmuss** [comment]
Closing old issue. Adding multi-timescale support to Nengo is a thing we've thought about (and will continue to think about), but it'd be a big change to Nengo core rather than something we do in Nengo OCL individually.
