### ISSUE TITLE
serialization

### ISSUE THREAD

**Issue by jaberg** [nengo/nengo-ocl#43]
Serialization would be a good thing to have, even immediately to make performance tuning easier.

I'm thinking: save all data as numpy arrays, and some sufficient summary of the various graphs to quickly rebuild kernels for whatever OCL device is used at load-time.

**Comment by drasmuss** [comment]
Would be good to have, but probably beyond the scope of planned Nengo OCL development any time soon, so closing this for now. We would reopen if there were a pressing need though.
